# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: erb.xhabafti@gmail.com
author_name: Erblin Xhabafti
preset_name: starter
project_name: algorand_cross_border-frontend

