# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.7.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: 119724168+paulaxho@users.noreply.github.com
author_name: paulaxho
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: algorand_terp

