# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.7.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: erb.xhabafti@gmail.com
author_name: Erblin Xhabafti
contract_name: score
deployment_language: python
preset_name: starter
project_name: FORT-contracts

